Import('qt_env')

env = qt_env.Clone()

env.AppendUnique(CPPDEFINES = [ 'INIEDITOR_LIBRARY' ])

env.AppendUnique(LIBS = [
    'shell32'
])

lib = env.SharedLibrary('iniEditor', env.Glob('*.cpp') + env.Glob('*.qrc'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
