Import('qt_env')

env = qt_env.Clone()

modules = [
    'Core',
    'Gui'
]

if env['QT_MAJOR_VERSION'] > 4:
    modules += [ 'Widgets' ]

env.EnableQt4Modules(['Qt' + n for n in modules],
                     debug = env['CONFIG'] == 'debug')

env.AppendUnique(CPPDEFINES = [ 'INIEDITOR_LIBRARY' ])

env.RequireLibraries('uibase')

env.AppendUnique(LIBS = [
    'shell32'
])

lib = env.SharedLibrary('iniEditor', env.Glob('*.cpp') + env.Glob('*.qrc'))
env.InstallPlugin(lib)
